apiVersion: v1
kind: Service
metadata:
  name: {{ include "teamspeak.fullname" . }}
  labels:
{{ include "teamspeak.labels" . | nindent 4 }}
{{- if .Values.service.annotations }}
  annotations:
{{ tpl (toYaml .Values.service.annotations) . | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.loadBalancerIP (eq (lower .Values.service.type) "loadbalancer") }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  ports:
    - port: {{ .Values.voice.port }}
      targetPort: voice
      protocol: UDP
      name: voice
    - port: {{ .Values.filetransfer.port }}
      targetPort: filetransfer
      protocol: TCP
      name: filetransfer
    - port: {{ .Values.webquery.port }}
      targetPort: webquery
      protocol: TCP
      name: webquery
  selector:
{{ include "teamspeak.selectorLabels" . | nindent 4 }}
